<?php
/**
 * Inner view file for Staff, Policy Research Scholars and Graduate Research Assistants pages
 *
 * From the IA, this view needs to display the following data:
 *  - Thumbnail of staff person
 *  - Name (post title? Or do we want first/last as entered in meta?)
 *  - First title
 *  - Phone number
 *  - email address
 *
 * Since these pages display the same information as the contact page, the content for these pages is generated by the
 * @see people-loop.php file and available as $strStaffLoop
 *
 *
 * You do not need to call get_header(), get_footer, get_sidebar() or breadcrumbs() as those are handled by outer
 * functions and/or views.
 *
 * @package WordPress
 * @subpackage IPP
 * @category theme
 * @category view
 * @author Paul Gilzow, Web Communications, University of Missouri
 * @copyright 2014 Curators of the University of Missouri
 *
 * @todo as of 201400601 the only difference between this page, and the contact page is that in the contact page we
 * include the post contents before the staff loop (which will be changed to a require).  However, it's entirely
 * reasonable to think that we might to at some point include the contents from the page entry in this page as well,
 * at which point, there really is no difference between these page and the contact page and at that point, they should
 * be merged into one file.  Wow, I really like to say "at ___ point".... And, run-on sentence much?
 *
 * @todo rename this file to better match its purpose?
 */
?>
<section aria-label="content" role="region">
    <?php //change to require ?>
    <?php echo $strStaffLoop; ?>
</section>
